name: Test Docker Compose Dev Build

on:
  push:
    paths:
      - '.devcontainer/**'
      - '.docker/dev/**'
  pull_request:
    paths:
      - '.devcontainer/**'
      - '.docker/dev/**'

jobs:
  validate-devcontainer-json:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Dev Containers CLI
        run: |
          npm install -g @devcontainers/cli

      - name: Validate devcontainer.json
        run: |
          devcontainer validate .devcontainer/devcontainer.json

  docker-compose-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker Compose
        run: |
          docker-compose -f .docker/dev/compose.yaml build
